name: Deploy Docker image to AWS

on:
  workflow_run:
    workflows: ['Publish Docker Image']
    types: [completed]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Stop old container
        run: docker stop uni-auth-docker-aws-cicd || true

      - name: Remove old container
        run: docker rm uni-auth-docker-aws-cicd || true

      - name: Delete old image
        run: docker rmi "${{secrets.DOCKERHUB_USERNAME}}"/ump-auth:latest || true

      - name: Pull the image from docker hub
        run: docker pull "${{secrets.DOCKERHUB_USERNAME}}"/ump-auth:latest

      - name: Start new image
        run: docker compose up -d
